from __future__ import annotations

import argparse

from tip_v1.cli.simulate_wallet_entries import WalletEntryExitConfig
from tip_v1.config import get_settings
from tip_v1.db.db import initialize_database
from tip_v1.pre_signal_engine.core import (
    build_pre_signal_simulation_report,
    simulate_pre_signals,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Simulate a pre-wallet signal dataset with controlled exits.")
    parser.add_argument("--db-path", help="Override the SQLite database path.")
    parser.add_argument("--dataset", required=True, help="Path to the CSV generated by build_pre_signal_dataset.")
    parser.add_argument("--threshold", type=float, default=0.70, help="Minimum score required to emit a signal.")
    parser.add_argument("--max-threshold", type=float, help="Optional upper score bound for band-pass filtering.")
    parser.add_argument("--take-profit", type=float, default=0.05, help="Take-profit threshold as decimal return.")
    parser.add_argument("--stop-loss", type=float, default=0.02, help="Stop-loss threshold as decimal return.")
    parser.add_argument("--max-hold", type=int, default=180, help="Maximum hold in seconds.")
    parser.add_argument("--entry-delay", type=int, default=0, help="Delay simulated entry by N seconds.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    settings = get_settings(args.db_path)
    initialize_database(settings)
    result = simulate_pre_signals(
        dataset_path=args.dataset,
        settings=settings,
        threshold=args.threshold,
        max_threshold=args.max_threshold,
        config=WalletEntryExitConfig(
            take_profit=args.take_profit,
            stop_loss=args.stop_loss,
            max_hold_seconds=args.max_hold,
            entry_delay_seconds=args.entry_delay,
        ),
    )
    print(build_pre_signal_simulation_report(result))


if __name__ == "__main__":
    main()
