from __future__ import annotations

import argparse

from tip_v1.cli.simulate_wallet_entries import WalletEntryExitConfig
from tip_v1.config import get_settings
from tip_v1.db.db import initialize_database
from tip_v1.pre_signal_engine.core import (
    build_pre_signal_threshold_sweep_report,
    load_pre_signal_dataset_csv,
    sweep_pre_signal_thresholds,
)


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Sweep thresholds for the pre-signal predictor and report score distributions.")
    parser.add_argument("--db-path", help="Override the SQLite database path.")
    parser.add_argument("--dataset", required=True, help="Path to the CSV generated by build_pre_signal_dataset.")
    parser.add_argument(
        "--thresholds",
        nargs="+",
        type=float,
        required=True,
        help="Threshold values to evaluate.",
    )
    parser.add_argument("--take-profit", type=float, default=0.05, help="Take-profit threshold as decimal return.")
    parser.add_argument("--stop-loss", type=float, default=0.02, help="Stop-loss threshold as decimal return.")
    parser.add_argument("--max-hold", type=int, default=180, help="Maximum hold in seconds.")
    parser.add_argument("--entry-delay", type=int, default=0, help="Delay simulated entry by N seconds.")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    settings = get_settings(args.db_path)
    initialize_database(settings)
    dataset_rows = load_pre_signal_dataset_csv(args.dataset)
    sweep_rows = sweep_pre_signal_thresholds(
        dataset_path=args.dataset,
        thresholds=args.thresholds,
        settings=settings,
        config=WalletEntryExitConfig(
            take_profit=args.take_profit,
            stop_loss=args.stop_loss,
            max_hold_seconds=args.max_hold,
            entry_delay_seconds=args.entry_delay,
        ),
    )
    print(
        build_pre_signal_threshold_sweep_report(
            dataset_path=args.dataset,
            rows=dataset_rows,
            sweep_rows=sweep_rows,
        )
    )


if __name__ == "__main__":
    main()
